package org.leoho;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.ArrayList;
import java.util.Random;

@EqualsAndHashCode
@Getter
@Setter
@ToString
public class Assignment {
    private String assignmentId;
    private String assignmentName;
    private double weight;
    private ArrayList<Integer> scores;
    private static int nextId = 1;

    /**
     * Calculates the average score for the assignment.
     */
    public void calcAssignmentAvg() {
        double sum = 0;

        for (int i = 0; i < scores.size(); i++) {
            sum += scores.get(i);
        }

        double avg = sum / scores.size();
    }

    /**
     * Generates random scores for all students in an assignment.
     * The scores are generated by a number in range [0, 10].
     * From there, each of those number sort them into their respective range
     * e.g. 0 -> range [0, 60)
     */
    public void generateRandomScore() {
        Random random = new Random();
        int score = 0;
        int rand = random.nextInt(0, 10 + 1);

        if (rand == 0) {
            score = random.nextInt(0, 60);
        } else if (rand == 1 || rand == 2) {
            score = random.nextInt(60, 70);
        } else if (rand == 3 || rand == 4) {
            score = random.nextInt(70, 80);
        } else if (rand == 5 || rand == 6 || rand == 7 || rand == 8) {
            score = random.nextInt(80, 90);
        } else if (rand == 9 || rand == 10) {
            score = random.nextInt(90, 100 + 1);
        }

        scores.add(score);
    }
}
